os:
  - linux
language: node_js
dist: bionic
services:
  - xvfb
node_js:
  - "10"
  - "8"
before_script:
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install metacity; fi"
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then metacity --sm-disable --replace 2> metacity.err & fi"
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then metacity-theme-viewer & fi"
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sleep 3; fi"
script:
  - npm install
  - npm test
